"""Celery task for executing data collection pipelines."""

import asyncio
import json
import logging

from celery.exceptions import SoftTimeLimitExceeded
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker

from app.core.celery_app import celery_app
from app.core.database import create_task_engine

logger = logging.getLogger(__name__)


def _run_async(coro):
    """Run an async coroutine in a new event loop (for Celery sync tasks)."""
    loop = asyncio.new_event_loop()
    try:
        return loop.run_until_complete(coro)
    finally:
        loop.close()


@celery_app.task(
    name="app.tasks.collection.execute_collection_task",
    bind=True,
    max_retries=1,
    soft_time_limit=600,
    time_limit=660,
)
def execute_collection_task(self, task_id: str):
    """Execute a data collection pipeline in background."""
    return _run_async(_execute_collection_async(task_id))


async def _execute_collection_async(task_id: str):
    """Run the collection pipeline for a task.

    Uses separate DB sessions for each phase to avoid connection timeouts
    during long-running scraping operations.
    """
    from app.models.collection_task import CollectionTask, CollectionResult
    from app.services.ai.collection_pipeline import run_collection_pipeline
    from app.core.settings_manager import load_settings_from_db
    from sqlalchemy import update
    from datetime import datetime

    engine = create_task_engine()
    session_factory = async_sessionmaker(engine, class_=AsyncSession, expire_on_commit=False)

    try:
        # ── Phase 0: Load task & settings, mark running ──
        task_data = None
        settings = None
        async with session_factory() as db:
            result = await db.execute(
                select(CollectionTask).where(CollectionTask.id == task_id)
            )
            task = result.scalar_one_or_none()
            if not task:
                logger.error("Collection task not found: %s", task_id)
                return {"status": "error", "reason": "task not found"}

            task.status = "running"
            task.last_run_status = "running"
            await db.commit()

            settings = await load_settings_from_db(db)

            # Snapshot task data we need (detach from session)
            task_data = {
                "id": task.id,
                "user_id": task.user_id,
                "name": task.name,
                "description": task.description,
                "target_urls": list(task.target_urls) if task.target_urls else None,
                "keywords": list(task.keywords) if task.keywords else None,
                "json_schema": task.json_schema,
                "scraping_instructions": task.scraping_instructions,
                "pipeline_id": task.pipeline_id,
                "vault_credential_ids": task.vault_credential_ids,
                "vault_api_key_ids": task.vault_api_key_ids,
                "scraping_engine": task.scraping_engine,
                "post_actions": task.post_actions,
            }

        # ── Phase 1: Run pipeline (no DB session needed) ──
        try:
            # Build a lightweight task-like object from snapshot
            from types import SimpleNamespace
            task_obj = SimpleNamespace(**task_data, _search_queries=None)

            pipeline_result = await run_collection_pipeline(
                task=task_obj,
                settings=settings,
            )

            # ── Phase 2: Save results in fresh session ──
            async with session_factory() as db:
                # Count total parsed items
                result_count = sum(len(items) for _, items in pipeline_result.parsed_items)
                run_status = "success" if result_count > 0 else "no_results"
                if result_count > 0:
                    run_message = f"{result_count}건 수집 완료"
                    if pipeline_result.parse_failure_count > 0:
                        run_message += f" (파싱 실패 {pipeline_result.parse_failure_count}/{pipeline_result.total_crawled_count}페이지)"
                elif pipeline_result.failure_reason:
                    run_message = pipeline_result.failure_reason
                else:
                    run_message = "데이터를 추출하지 못했습니다"

                # Persist json_schema/scraping_instructions/target_urls
                # generated by Stage 1 (avoids re-running LLM every time)
                schema_updates = {}
                if task_obj.json_schema and task_obj.json_schema != task_data.get("json_schema"):
                    schema_updates["json_schema"] = task_obj.json_schema
                if task_obj.scraping_instructions and task_obj.scraping_instructions != task_data.get("scraping_instructions"):
                    schema_updates["scraping_instructions"] = task_obj.scraping_instructions
                if schema_updates:
                    await db.execute(
                        update(CollectionTask)
                        .where(CollectionTask.id == task_id)
                        .values(**schema_updates)
                    )

                # Create CollectionResult objects from parsed data
                raw_text_map = {url: text for url, text in pipeline_result.raw_texts}
                for url, items in pipeline_result.parsed_items:
                    for item_data in items:
                        db.add(CollectionResult(
                            task_id=task_data["id"],
                            user_id=task_data["user_id"],
                            pipeline_id=task_data.get("pipeline_id"),
                            source_url=url,
                            raw_text=raw_text_map.get(url, "")[:5000],
                            parsed_data=item_data,
                        ))

                # Export results to /AI Workspace/Scouts/
                file_export_failed = False
                if result_count > 0:
                    try:
                        from app.services.workspace_service import (
                            ensure_workspace_folders,
                            save_workspace_file,
                        )
                        await ensure_workspace_folders(task_data["user_id"], db)

                        all_items = []
                        for url, items in pipeline_result.parsed_items:
                            for item in items:
                                all_items.append({"source": url, "data": item})

                        from zoneinfo import ZoneInfo
                        ts = datetime.now(ZoneInfo("Asia/Seoul")).strftime("%y%m%d%H%M%S")
                        task_name = task_data["name"][:20].strip()
                        filename = f"{task_name}_{ts}.json"
                        content = json.dumps(
                            all_items, ensure_ascii=False, indent=2,
                        )
                        await save_workspace_file(
                            user_id=task_data["user_id"],
                            folder="/AI Workspace/Scouts",
                            filename=filename,
                            content=content,
                            mime_type="application/json",
                            db=db,
                        )
                    except Exception as e:
                        logger.warning(
                            "Failed to export collection to Scouts folder: %s", e,
                        )
                        file_export_failed = True

                if file_export_failed:
                    run_message += " (파일 저장 실패)"

                # Record LLM token usage
                if pipeline_result.total_input_tokens or pipeline_result.total_output_tokens:
                    from app.services.ai.token_accounting import record_usage
                    await record_usage(
                        db, task_data["user_id"],
                        pipeline_result.total_input_tokens,
                        pipeline_result.total_output_tokens,
                        source="mining",
                    )

                await db.execute(
                    update(CollectionTask)
                    .where(CollectionTask.id == task_id)
                    .values(
                        status="active",
                        last_run_status=run_status,
                        last_run_message=run_message,
                        last_run_at=datetime.utcnow(),
                        run_count=CollectionTask.run_count + 1,
                    )
                )
                await db.commit()

                logger.info(
                    "Collection task completed: %s, results=%d, status=%s",
                    task_id, result_count, run_status,
                )
                return {"status": run_status, "results": result_count}

        except SoftTimeLimitExceeded:
            logger.warning("Collection task timed out: %s", task_id)
            try:
                async with session_factory() as err_db:
                    await err_db.execute(
                        update(CollectionTask)
                        .where(CollectionTask.id == task_id)
                        .values(
                            status="active",
                            last_run_status="timeout",
                            last_run_message="작업 시간 초과 (10분 제한)",
                            last_run_at=datetime.utcnow(),
                            run_count=CollectionTask.run_count + 1,
                        )
                    )
                    await err_db.commit()
            except Exception:
                pass
            return {"status": "timeout"}

        except Exception as e:
            logger.error("Collection task failed: %s — %s", task_id, e)
            error_msg = str(e)
            # Map common errors to user-friendly messages
            if "403" in error_msg or "Forbidden" in error_msg:
                friendly = "웹수집 방지 정책으로 인한 차단"
            elif "404" in error_msg or "Not Found" in error_msg:
                friendly = "대상 페이지를 찾을 수 없음"
            elif "timeout" in error_msg.lower() or "Timeout" in error_msg:
                friendly = "대상 서버 응답 시간 초과"
            elif "connection" in error_msg.lower():
                friendly = "대상 서버 연결 실패"
            else:
                friendly = error_msg[:200]
            try:
                async with session_factory() as err_db:
                    await err_db.execute(
                        update(CollectionTask)
                        .where(CollectionTask.id == task_id)
                        .values(
                            status="active",
                            last_run_status="failed",
                            last_run_message=friendly,
                            last_run_at=datetime.utcnow(),
                            run_count=CollectionTask.run_count + 1,
                        )
                    )
                    await err_db.commit()
            except Exception:
                pass
            return {"status": "failed", "reason": str(e)}
    finally:
        await engine.dispose()
